project/app/Http/routes.php
<?php

/**
 * Routes for users & guests.
 */
Route::get('/', 'UserController@userFeeds');
Route::get('home', 'UserController@userFeeds');
Route::get('login', 'UserController@getLogin');
Route::get('register', 'UserController@getRegister');

/**
 * Routes for posts and forums
 */
Route::any("forum/{slug}", array(
    "as" => "home",
    "uses" => "ForumController@index"
));

Route::any("post/{slug}", array(
    "as" => "home",
    "uses" => "PostController@index"
));

/**
 * Routes after logged in.
 */

Route::get('profile/editpassword', 'UserController@getEditPassword');

Route::group(array('after' => 'auth'), function () {

    /**
     * Get user profile methods (Get Methods)
     */

    Route::get('profile/editprofile', 'UserController@getEditProfile');
    Route::get('profile/avatar', 'UserController@getUploadAvatar');
    Route::get('profile/cover', 'UserController@getUploadCover');
    Route::get('pinned', 'UserController@postFollowing');
    Route::get('logout', 'UserController@logout');

    /**
     * Get forum methods (Get Methods)
     */
    Route::get('managetopic/avatar/{slug}', 'ForumController@getUploadForumAvatar');
    Route::get('managetopic/cover/{slug}', 'ForumController@getUploadForumCover');
    Route::get('managetopic/settings/{slug}', 'ForumController@editTopic');
    Route::get('deletetopic/delete/{slug}', 'ForumController@deleteTopic');
    Route::get('topic/create', 'ForumController@getCreateTopic');
    Route::get('topic/manage', 'ForumController@getManageTopic');

    /**
     * Post user profile methods (Post Methods)
     */
    Route::post('updatepassword', 'UserController@updatePassword');
    Route::post('updateprofile', 'UserController@updateProfile');
    Route::post('updateavatar', 'UserController@updateAvatar');
    Route::post('updatecover', 'UserController@updateCover');
    Route::post('register', 'UserController@postRegister');
    Route::post('login', 'UserController@postLogin');

    /**
     * Forum Following methods (Resource Routes)
     */
    Route::resource('followtopic', 'ForumFollowController@store');
    Route::resource('unfollowtopic', 'ForumFollowController@destroy');

    /**
     * Methods for pinning posts (Post Methods)
     */
    Route::post('unfollow', 'FollowController@destroy');
    Route::post('follow', 'FollowController@store');

    /**
     * Post forum (Post Methods)
     */
    Route::post('updateforumavatar', 'ForumController@updateForumAvatar');
    Route::post('updateforumcover', 'ForumController@updateForumCover');
    Route::post('createtopic', 'ForumController@createTopic');
    Route::post('updatetopic', 'ForumController@updateTopic');

    /**
     * Post posts (Post Methods)
     */
    Route::post('submitpost', 'PostController@store');
    Route::post('updatepost', 'PostController@update');
    Route::post('deletepost', 'PostController@destroy');

    /**
     * Post reply (Post Methods)
     */
    Route::post('postcomment', 'ReplyController@store');
    Route::post('updatecomment', 'ReplyController@update');
    Route::post('deletecomment', 'ReplyController@destroy');


    /**
     * Get admin home (Get Methods)
     */
    Route::get('admin', 'AdminController@index');
    Route::get('admin/home', 'AdminController@home');

    /**
     * Get admin manage posts (Get Methods)
     */
    Route::get('admin/manageposts', 'AdminController@managePosts');
    Route::get('admin/editpost/{id}', 'AdminController@editPost');
    Route::get('admin_deletepost/{id}', 'AdminController@deletePost');

    /**
     * Post admin update posts (Post Methods)
     */
    Route::post('admin_updatepost', 'AdminController@updatePost');

    /**
     * Get admin manage topics (Get Methods)
     */
    Route::get('admin/createtopic', 'AdminController@createTopic');
    Route::get('admin/managetopics', 'AdminController@manageTopics');
    Route::get('admin/topicedit/{id}', 'AdminController@editTopic');
    Route::get('admin_deletetopic/{id}', 'AdminController@deleteTopic');

    /**
     * Get admin manage users (Get Methods)
     */
    Route::get('admin/manageusers', 'AdminController@manageUsers');
    Route::get('admin/createuser', 'AdminController@createUser');
    Route::get('admin/userroles', 'AdminController@assignRole');
    Route::get('admin_deleteuser/{id}', 'AdminController@deleteUser');
    Route::get('admin/edituser/{id}', 'AdminController@editUser');

    /**
     * Post admin manage users (Post Methods)
     */
    Route::post('admin_updatuser', 'AdminController@updateUser');
    Route::post('admin/postcreateuser', 'AdminController@insertUser');
    Route::post('admin_updatuserrole', 'AdminController@updateUserRole');

    /**
     * Admin Settings
     */
    Route::get('admin/settings', 'AdminController@settings');
    Route::post('admin_updatesettings', 'AdminController@updateAdminSettings');

    /**
     * Forum and post (Resource Routes)
     */
    Route::resource('forum', 'ForumController');
    Route::resource('post', 'PostController');

//    Route::resource('follow', 'FollowController');
//    Route::get('topiclist', 'ForumController@listTopics');
});

project/resources/views/admin/topic/create.blade.php
@extends('admin.template.index')
@section('content')
<div class="page-margin"></div>
<div class="float-right span74">
    {!! Form::open(array(  'url' => array('createtopic'))) !!}
        <div class="form-container">
            <div class="form-header">
                <i class="icon-lightbulb-o"></i> Create Topic
            </div>
            @if($errors->any())
                <div class="fail-message" style="display: block;">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form-input-wrapper">
                <label class="float-left span25">
                    Category:
                </label>
                <div class="input float-left span65">
                    @include('main.include.category_list')
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span25">
                    Name:
                </label>
                <div class="input float-left span65">
                    <input type="text" name="name" placeholder="Name of your page" data-placeholder="Name of your page">
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span25">
                    Address:
                </label>
                <div class="input float-left span65">
                    <input type="text" name="address" data-placeholder="/webaddress" placeholder="/webaddress" autocomplete="off">
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span25">
                    Description:
                </label>
                <div class="input float-left span65">
                    <textarea class="auto-grow-input" name="description"  valign="top" name="page_about" placeholder="Write about your page..." data-placeholder="Write about your page..."></textarea>
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <button class="active">
                    <i class="icon-flask"></i> Create
                </button>
            </div>
        </div>
    {!! Form::close() !!}
</div>
@endsection

project/resources/views/admin/topic/edit.blade.php
@extends('admin.template.index')
@section('content')
    <div class="page-margin"></div>
    <div class="float-right span74">
        {!! Form::open(array(  'url' => array('updatetopic'))) !!}
        <input type="hidden" name="gategory" value="{{$forum->category->id}}">
        <input type="hidden" name="forum" value="{{ $forum->id }}">
        <div class="form-container">
            <div class="form-header">
                <i class="icon-cog"></i> Edit Topic
            </div>
            @if($errors->any())
                <div class="fail-message" style="display: block;">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    Category: <br><strong>{{$forum->category->name}}</strong>
                </label>
                <div class="input float-left span70">
                    @include('main.include.category_list')
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    Name:
                </label>
                <div class="input float-left span70">
                    <input type="text" name="name"  value="{{$forum->name}}" placeholder="Name of your page" data-placeholder="Name of your page">
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    Address:
                </label>
                <div class="input float-left span70">
                    <input type="text" name="address" value="{{$forum->slug}}" autocomplete="off">
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    Description:
                </label>
                <div class="input float-left span70">
                    <textarea class="auto-grow-input" name="description"  rows="10" valign="top" name="page_about" placeholder="Write about your page..." data-placeholder="Write about your page...">{{$forum->desc}}</textarea>
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="form-input-wrapper">
                <button class="active">
                    <i class="icon-save progress-icon"></i>
                    Save Changes
                </button>

                <button class="delete">
                    <a href="/admin_deletetopic/{{$forum->id}}"><i class="icon-trash-o"></i> Remove</a>
                </button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

project/resources/views/admin/topic/manage.blade.php
@extends('admin.template.index')
@section('content')
    <div class="page-margin"></div>
    <div class="float-right span74">
        <div class="list-wrapper">
            <div class="list-header">
                <div class="float-left">
                    <i class="icon-file-o"></i> Manage Topics
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="list-column">
                <table>
                    <tbody>
                    @foreach($forums as $forum)
                        <tr>
                            <td width="5%">{!! $forum->id !!}</td>
                            <td width="60%">{!! link_to_route('forum.show',  $forum->name, array($forum->slug)) !!}</td>
                            <td width="5%"><a href="/admin/topicedit/{{$forum->id}}">Edit</a></td>
                            <td width="5%">
                                <button class="delete">
                                    <a href="/admin_deletetopic/{{$forum->id}}"><i class="icon-trash-o"></i></a>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection