project/app/Http/routes.php
<?php

/**
 * Routes for users & guests.
 */
Route::get('/', 'UserController@userFeeds');
Route::get('home', 'UserController@userFeeds');
Route::get('login', 'UserController@getLogin');
Route::get('register', 'UserController@getRegister');

/**
 * Routes for posts and forums
 */
Route::any("forum/{slug}", array(
    "as" => "home",
    "uses" => "ForumController@index"
));

Route::any("post/{slug}", array(
    "as" => "home",
    "uses" => "PostController@index"
));

/**
 * Routes after logged in.
 */

Route::get('profile/editpassword', 'UserController@getEditPassword');

Route::group(array('after' => 'auth'), function () {

    /**
     * Get user profile methods (Get Methods)
     */

    Route::get('profile/editprofile', 'UserController@getEditProfile');
    Route::get('profile/avatar', 'UserController@getUploadAvatar');
    Route::get('profile/cover', 'UserController@getUploadCover');
    Route::get('pinned', 'UserController@postFollowing');
    Route::get('logout', 'UserController@logout');

    /**
     * Get forum methods (Get Methods)
     */
    Route::get('managetopic/avatar/{slug}', 'ForumController@getUploadForumAvatar');
    Route::get('managetopic/cover/{slug}', 'ForumController@getUploadForumCover');
    Route::get('managetopic/settings/{slug}', 'ForumController@editTopic');
    Route::get('deletetopic/delete/{slug}', 'ForumController@deleteTopic');
    Route::get('topic/create', 'ForumController@getCreateTopic');
    Route::get('topic/manage', 'ForumController@getManageTopic');

    /**
     * Post user profile methods (Post Methods)
     */
    Route::post('updatepassword', 'UserController@updatePassword');
    Route::post('updateprofile', 'UserController@updateProfile');
    Route::post('updateavatar', 'UserController@updateAvatar');
    Route::post('updatecover', 'UserController@updateCover');
    Route::post('register', 'UserController@postRegister');
    Route::post('login', 'UserController@postLogin');

    /**
     * Forum Following methods (Resource Routes)
     */
    Route::resource('followtopic', 'ForumFollowController@store');
    Route::resource('unfollowtopic', 'ForumFollowController@destroy');

    /**
     * Methods for pinning posts (Post Methods)
     */
    Route::post('unfollow', 'FollowController@destroy');
    Route::post('follow', 'FollowController@store');

    /**
     * Post forum (Post Methods)
     */
    Route::post('updateforumavatar', 'ForumController@updateForumAvatar');
    Route::post('updateforumcover', 'ForumController@updateForumCover');
    Route::post('createtopic', 'ForumController@createTopic');
    Route::post('updatetopic', 'ForumController@updateTopic');

    /**
     * Post posts (Post Methods)
     */
    Route::post('submitpost', 'PostController@store');
    Route::post('updatepost', 'PostController@update');
    Route::post('deletepost', 'PostController@destroy');

    /**
     * Post reply (Post Methods)
     */
    Route::post('postcomment', 'ReplyController@store');
    Route::post('updatecomment', 'ReplyController@update');
    Route::post('deletecomment', 'ReplyController@destroy');


    /**
     * Get admin home (Get Methods)
     */
    Route::get('admin', 'AdminController@index');
    Route::get('admin/home', 'AdminController@home');

    /**
     * Get admin manage posts (Get Methods)
     */
    Route::get('admin/manageposts', 'AdminController@managePosts');
    Route::get('admin/editpost/{id}', 'AdminController@editPost');
    Route::get('admin_deletepost/{id}', 'AdminController@deletePost');

    /**
     * Post admin update posts (Post Methods)
     */
    Route::post('admin_updatepost', 'AdminController@updatePost');

    /**
     * Get admin manage topics (Get Methods)
     */
    Route::get('admin/createtopic', 'AdminController@createTopic');
    Route::get('admin/managetopics', 'AdminController@manageTopics');
    Route::get('admin/topicedit/{id}', 'AdminController@editTopic');
    Route::get('admin_deletetopic/{id}', 'AdminController@deleteTopic');

    /**
     * Get admin manage users (Get Methods)
     */
    Route::get('admin/manageusers', 'AdminController@manageUsers');
    Route::get('admin/createuser', 'AdminController@createUser');
    Route::get('admin/userroles', 'AdminController@assignRole');
    Route::get('admin_deleteuser/{id}', 'AdminController@deleteUser');
    Route::get('admin/edituser/{id}', 'AdminController@editUser');

    /**
     * Post admin manage users (Post Methods)
     */
    Route::post('admin_updatuser', 'AdminController@updateUser');
    Route::post('admin/postcreateuser', 'AdminController@insertUser');
    Route::post('admin_updatuserrole', 'AdminController@updateUserRole');

    /**
     * Admin Settings
     */
    Route::get('admin/settings', 'AdminController@settings');
    Route::post('admin_updatesettings', 'AdminController@updateAdminSettings');

    /**
     * Forum and post (Resource Routes)
     */
    Route::resource('forum', 'ForumController');
    Route::resource('post', 'PostController');

//    Route::resource('follow', 'FollowController');
//    Route::get('topiclist', 'ForumController@listTopics');
});

project/app/Models/Post.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;

/**
 * Class Post
 * @package App\Models
 */
class Post extends Model
{

    /**
     * @var string
     */
    protected $table = 'post';
    /**
     * @var array
     */
    protected $guarded = array();

    /**
     * @var array
     */
    public static $rules = array(
        'title' => 'required',
        'body' => 'required',
        'slug' => 'unique:posts'
    );

    /**
     * A post belongs to a user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    /**
     * A post user belongs to a group
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function group()
    {
        return $this->belongsTo('App\Models\Group', 'group_id');
    }

    /**
     * A post has many replies
     * @return mixed
     */
    public function replies()
    {
        return $this->hasMany('App\Models\Reply')->orderBy('created_at', 'ASC');
    }

    /**
     * Aggretion relationship, post belongs to forum and only forum
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function forum()
    {
        return $this->belongsTo('App\Models\Forum', 'forum_id');
    }

    /**
     * A post has many followers (Pinners)
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function followers()
    {
        return $this->belongsToMany('App\Models\User', 'following', 'post_id', 'user_id');
    }

}

project/app/Http/Controllers/PostController.php
<?php namespace App\Http\Controllers;

use App\Models\Forum;
use App\Models\Following;
use App\Models\Feed;
use App\Models\Post;
use App\Models\Reply;
use Request;
use Illuminate\Support\Str;
use Input, Validator, Auth;
use Carbon\Carbon;
use View;

/**
 * Class PostController
 * @package App\Http\Controllers
 */
class PostController extends Controller
{
    /**
     * Render posts according to is given id, collect all of its data,
     * check if logged in and render its page with all of its data passed.
     * @param $id
     * @return mixed
     */
    public function index($id)
    {
        $post = Post::where('id', $id)->first();
        $forums = Forum::orderBy('created_at')->get();
        $userController = new UserController();
        $followController = new FollowController();

        if (!Auth::guest()) {
            $checkFollowing = $followController->checkFollowing(Auth::user()->id);
        }
        $checkFollowing[] = NULL;
        $isAdmin = $userController->isAdmin();

        return View::make('main.post.post_single')
            ->with('checkFollowing', $checkFollowing)
            ->with('isAdmin', $isAdmin)
            ->with('forums', $forums)
            ->with('post', $post);
    }


    /**
     * Check if logged in, validate all inputs, check for its existance.
     * If a post exist, then randomize the posts title. Otherwise,
     * save the post and save a record for user feeds.
     * @return $this
     */
    public function store()
    {
        if (!Auth::guest()) {
            $input = Input::all();
            $v = Validator::make($input, Post::$rules);
            if ($v->passes()) {
                $validate = Post::where('title', Input::get('title'))->first();
                $post = new Post;
                $post->title = Input::get('title');
                $post->body = Input::get('body');

                if ($validate) {
                    $post->slug = Str::slug(Input::get('title') . '_' . str_random(3));
                } else {
                    $post->slug = Str::slug(Input::get('title'));
                }

                $post->user_id = Auth::user()->id;
                $post->forum_id = Input::get('forum_id');
                $post->save();

                $Feed = new Feed();
                $Feed->post_id = $post->id;
                $Feed->forum_id = $post->forum_id;
                $Feed->save();

            }
            return redirect()->back()->withErrors($v);
        }
    }

    /**
     * Check if logged in, validate its existance and its orignal poster.
     * Give rights to update if admin or the original poster and update each
     * field within table.
     */
    public function update()
    {
        if (!Auth::guest()) {
            $validate = Post::where('id', Input::get('post_id'))->where('user_id', Auth::user()->id)->first();
            $userController = new UserController();
            if ($validate || $userController->isAdmin()) {
                Post::where('id', Input::get('post_id'))->update(
                    array(
                        'title' => Input::get('post_title'),
                        'body' => Input::get('post_value'),
                        'slug' => Input::get('post_title'),
                    )
                );
            }
        }
    }

    /**
     * Check if logged in, validate the posts existance.
     * Check if admin or the original poster and remove the record accoring to
     * user rights.
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy()
    {
        if (!Auth::guest()) {
            $validate = Post::where('id', Input::get('post_id'))->where('user_id', Auth::user()->id)->first();
            $userController = new UserController();
            if (Input::get('user_id') == Auth::user()->id) {
                if ($validate || $userController->isAdmin()) {
                    Post::find(Input::get('post_id'))->delete();
                    Following::where('post_id', Input::get('post_id'))->delete();
                    Reply::where('post_id', Input::get('post_id'))->delete();
                    Feed::where('post_id', Input::get('post_id'))->delete();
                    return redirect()->back();
                }
            }
        }
    }

    /**
     * Simple BB code method that is escaped. Used with
     * Regex method in javascript, for posting, updating comments.
     * @param $text
     * @return mixed
     */
    public function showBBcodes($text)
    {
        $text = nl2br(e($text));
        $find = array(
            '~\[b\](.*?)\[/b\]~s',
            '~\[i\](.*?)\[/i\]~s',
            '~\[u\](.*?)\[/u\]~s',
            '~\[quote\](.*?)\[/quote\]~s',
            '~\[size=(.*?)\](.*?)\[/size\]~s',
            '~\[color=(.*?)\](.*?)\[/color\]~s',
            '~\[url\]((?:ftp|https?)://.*?)\[/url\]~s',
            '~\[img\](https?://.*?\.(?:jpg|jpeg|gif|png|bmp))\[/img\]~s',
            "/( |^);P( |$)/",
            "/( |^):P( |$)/",
            "/( |^):D( |$)/",
            "/( |^)KD( |$)/",
            "/( |^)XC( |$)/",
            "/( |^)TT_TT( |$)/",
            "/( |^):inlove( |$)/",
            "/( |^):sungrassface( |$)/",
            "/( |^):confused( |$)/",
            "/( |^):smailface( |$)/",
            "/( |^):facesmail( |$)/",
            "/( |^):smillingeye( |$)/",
            "/( |^):halo( |$)/",
            "/( |^):woo( |$)/",
        );

        $replace = array(
            '<b>$1</b>',
            '<i>$1</i>',
            '<span style="text-decoration:underline;">$1</span>',
            '<pre>$1</' . 'pre>',
            '<span style="font-size:$1px;">$2</span>',
            '<span style="color:$1;">$2</span>',
            '<a href="$1">$1</a>',
            '<img width="100%" src="$1" alt="" />',
            '<img width="25px" src="'.emoticons.'hello.png" alt="" />',
            '<img width="25px" src="'.emoticons.'smaillike.png" alt="" />',
            '<img width="25px" src="'.emoticons.'smallopen.png" alt="" />',
            '<img width="25px" src="'.emoticons.'smailyes.png" alt="" />',
            '<img width="25px" src="'.emoticons.'bandege.png" alt="" />',
            '<img width="25px" src="'.emoticons.'crying.png" alt="" />',
            '<img width="25px" src="'.emoticons.'love.png" alt="" />',
            '<img width="25px" src="'.emoticons.'sungrassface.png" alt="" />',
            '<img width="25px" src="'.emoticons.'confused.png" alt="" />',
            '<img width="25px" src="'.emoticons.'smailface.png" alt="" />',
            '<img width="25px" src="'.emoticons.'facesmail.png" alt="" />',
            '<img width="25px" src="'.emoticons.'smillingeye.png" alt="" />',
            '<img width="25px" src="'.emoticons.'halo.png" alt="" />',
            '<img width="25px" src="'.emoticons.'woo.png" alt="" />',
        );

        return preg_replace($find, $replace, $text);
    }


}

project/resources/views/admin/post/edit.blade.php
@extends('admin.template.index')
@section('content')
    <div class="page-margin"></div>
    <div class="float-right span74">
        {!! Form::open(array(  'url' => array('admin_updatepost'))) !!}
        <input type="hidden" name="post_id" value="{{ $post->id }}">
            <div class="form-container">
                <div class="form-header">
                    <i class="icon-comment-o"></i> Edit Post
                </div>
                @if($errors->any())
                    <div class="fail-message" style="display: block;">
                        <strong>Whoops!</strong> There were some problems with your input.
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-input-wrapper">
                    <label class="float-left span15">
                       Post Title:
                    </label>
                    <div class="input float-left span80">
                        <input type="text" name="title" value="{{$post->title}} " autocomplete="off">
                    </div>
                    <div class="float-clear"></div>
                </div>
                <div class="form-input-wrapper">
                    <label class="float-left span15">
                        Post:
                    </label>
                    <div class="input float-left span80">
                        <textarea  name="body" rows="5" valign="top">{{$post->body}}</textarea>
                    </div>
                    <div class="float-clear"></div>
                </div>
                <div class="form-input-wrapper">
                    <button class="active">
                        <i class="icon-save progress-icon"></i>
                        Save Changes
                    </button>

                    <button class="delete">
                        <a href="/admin_deletepost/{{$post->id}}"><i class="icon-trash-o"></i> Remove</a>
                    </button>

                </div>
                {!!Form::close() !!}
            </div>
        </form>

    </div>
@endsection

project/resources/views/admin/post/manage.blade.php
@extends('admin.template.index')
@section('content')
    <div class="page-margin"></div>
    <div class="float-right span74">
        <div class="list-wrapper">
            <div class="list-header">
                <div class="float-left">
                    <i class="icon-comment-o"></i> Manage Posts
                </div>
                <div class="float-clear"></div>
            </div>
            <div class="list-column">
                <table>
                    <tbody>
                    @foreach($post as $p)
                        <tr>
                            <td width="5%">{!! $p->id !!}</td>
                            <td width="60%">{!! link_to_route('post.show',  $p->title, array($p->id)) !!}</td>
                            <td width="5%"><a href="/admin/editpost/{{$p->id}}">Edit</a></td>
                            <td width="5%">
                                <button class="delete">
                                    <a href="/admin_deletepost/{{$p->id}}"><i class="icon-trash-o"></i></a>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection